### ISSUE TITLE
Fails to build on Debian 11.3

### ISSUE THREAD

**Issue by millerjs2** [rvido/iManager#14]
Trying to build on Debian 11.3. Fails with the following errors:

```make -C /lib/modules/5.10.0-13-amd64/build M=/home/john/iManager clean
make[1]: Entering directory '/usr/src/linux-headers-5.10.0-13-amd64'
make[1]: Leaving directory '/usr/src/linux-headers-5.10.0-13-amd64'
rm -f -rf *.bak
make -C /lib/modules/5.10.0-13-amd64/build M=/home/john/iManager modules
make[1]: Entering directory '/usr/src/linux-headers-5.10.0-13-amd64'
  CC [M]  /home/john/iManager/imanager-core.o
/home/john/iManager/imanager-core.c: In function ‘imanager_register_cells’:
/home/john/iManager/imanager-core.c:806:13: error: assignment of read-only location ‘devs[i++]’
  806 |   devs[i++] = imanager_devs[IMANAGER_BACKLIGHT];
      |             ^
/home/john/iManager/imanager-core.c:809:13: error: assignment of read-only location ‘devs[i++]’
  809 |   devs[i++] = imanager_devs[IMANAGER_GPIO];
      |             ^
/home/john/iManager/imanager-core.c:812:13: error: assignment of read-only location ‘devs[i++]’
  812 |   devs[i++] = imanager_devs[IMANAGER_HWMON];
      |             ^
/home/john/iManager/imanager-core.c:815:13: error: assignment of read-only location ‘devs[i++]’
  815 |   devs[i++] = imanager_devs[IMANAGER_SMB];
      |             ^
/home/john/iManager/imanager-core.c:818:13: error: assignment of read-only location ‘devs[i++]’
  818 |   devs[i++] = imanager_devs[IMANAGER_WDT];
      |             ^
/home/john/iManager/imanager-core.c: In function ‘imanager_add_attribute’:
/home/john/iManager/imanager-core.c:222:3: warning: this statement may fall through [-Wimplicit-fallthrough=]
  222 |   switch (attr->did) {
      |   ^~~~~~
/home/john/iManager/imanager-core.c:238:2: note: here
  238 |  case ADC:
      |  ^~~~
/home/john/iManager/imanager-core.c:239:3: warning: this statement may fall through [-Wimplicit-fallthrough=]
  239 |   switch (attr->did) {
      |   ^~~~~~
/home/john/iManager/imanager-core.c:281:2: note: here
  281 |  case PWM:
      |  ^~~~
/home/john/iManager/imanager-core.c:282:3: warning: this statement may fall through [-Wimplicit-fallthrough=]
  282 |   switch (attr->did) {
      |   ^~~~~~
/home/john/iManager/imanager-core.c:315:2: note: here
  315 |  case SMB:
      |  ^~~~
/home/john/iManager/imanager-core.c:316:3: warning: this statement may fall through [-Wimplicit-fallthrough=]
  316 |   switch (attr->did) {
      |   ^~~~~~
/home/john/iManager/imanager-core.c:334:2: note: here
  334 |  case IRQ:
      |  ^~~~
make[3]: *** [/usr/src/linux-headers-5.10.0-13-common/scripts/Makefile.build:285: /home/john/iManager/imanager-core.o] Error 1
make[2]: *** [/usr/src/linux-headers-5.10.0-13-common/Makefile:1846: /home/john/iManager] Error 2
make[1]: *** [/usr/src/linux-headers-5.10.0-13-common/Makefile:185: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.10.0-13-amd64'
make: *** [Makefile:29: modules] Error 2```

**Comment by sethwilhelm** [comment]
I dealt with this a few months back and don't remember all the details.  The biggest change is because the mfd_cell struct change.

I also don't claim to be an expert, which is why I did not post this previously.  Hope this helps.

``` diff
diff --git a/imanager-core.c b/imanager-core.c
index bebf94d..4d9ee51 100644
--- a/imanager-core.c
+++ b/imanager-core.c
@@ -13,6 +13,7 @@
 
 #define pr_fmt(fmt) KBUILD_MODNAME ": " fmt
 
+#include <linux/acpi.h>
 #include <linux/bitops.h>
 #include <linux/byteorder/generic.h>
 #include <linux/delay.h>
@@ -235,6 +236,7 @@ static void imanager_add_attribute(struct imanager_ec_data *ec,
 			wdt->num++;
 			break;
 		}
+		break;
 	case ADC:
 		switch (attr->did) {
 		case ADC12VS0:
@@ -278,6 +280,7 @@ static void imanager_add_attribute(struct imanager_ec_data *ec,
 			adc->num++;
 			break;
 		}
+		break;
 	case PWM:
 		switch (attr->did) {
 		case CPUFAN_2P:
@@ -312,6 +315,7 @@ static void imanager_add_attribute(struct imanager_ec_data *ec,
 			bl->num++;
 			break;
 		}
+		break;
 	case SMB:
 		switch (attr->did) {
 		case SMBEEPROM:
@@ -331,12 +335,14 @@ static void imanager_add_attribute(struct imanager_ec_data *ec,
 			i2c->num++;
 			break;
 		}
+		break;
 	case IRQ:
 		if (attr->did == WDIRQ) {
 			wdt->attr[0] = attr;
 			wdt->num++;
 			break;
 		}
+		break;
 	}
 }
 
@@ -778,50 +784,48 @@ enum imanager_cells {
  * iManager devices which are available via firmware.
  */
 
-static const struct mfd_cell imanager_devs[] = {
-	[IMANAGER_BACKLIGHT] = {
-		.name = "imanager-backlight",
-	},
-	[IMANAGER_GPIO] = {
-		.name = "imanager-gpio",
-	},
-	[IMANAGER_HWMON] = {
-		.name = "imanager-hwmon",
-	},
-	[IMANAGER_SMB] = {
-		.name = "imanager-smbus",
-	},
-	[IMANAGER_WDT] = {
-		.name = "imanager-wdt",
-	},
+static const char * imanager_dev_names[] = {
+	[IMANAGER_BACKLIGHT] = "imanager-backlight",
+	[IMANAGER_GPIO]      = "imanager-gpio",
+	[IMANAGER_HWMON]     = "imanager-hwmon",
+	[IMANAGER_SMB]       = "imanager-smbus",
+	[IMANAGER_WDT]       = "imanager-wdt",
 };
 
 static int imanager_register_cells(struct imanager_device_data *imgr)
 {
 	struct imanager_ec_data *ec = &imgr->ec;
-	struct mfd_cell devs[ARRAY_SIZE(imanager_devs)];
+	struct mfd_cell devs[ARRAY_SIZE(imanager_dev_names)] = { 0 };
+	int ret = 0;
 	int i = 0;
 
-	if (ec->features & IMANAGER_FEATURE_BACKLIGHT)
-		devs[i++] = imanager_devs[IMANAGER_BACKLIGHT];
+	if (ec->features & IMANAGER_FEATURE_BACKLIGHT) {
+		devs[i++].name = imanager_dev_names[IMANAGER_BACKLIGHT];
+		dev_info(imgr->dev, "iManager: backlight");
+	}
 
-	if (ec->features & IMANAGER_FEATURE_GPIO)
-		devs[i++] = imanager_devs[IMANAGER_GPIO];
+	if (ec->features & IMANAGER_FEATURE_GPIO) {
+		devs[i++].name = imanager_dev_names[IMANAGER_GPIO];
+		dev_info(imgr->dev, "iManager: gpio");
+	}
 
-	if (ec->features & IMANAGER_FEATURE_HWMON_ADC)
-		devs[i++] = imanager_devs[IMANAGER_HWMON];
+	if (ec->features & IMANAGER_FEATURE_HWMON_ADC) {
+		devs[i++].name = imanager_dev_names[IMANAGER_HWMON];
+		dev_info(imgr->dev, "iManager: hwmon");
+	}
 
-	if (ec->features & IMANAGER_FEATURE_SMBUS)
-		devs[i++] = imanager_devs[IMANAGER_SMB];
+	if (ec->features & IMANAGER_FEATURE_SMBUS) {
+		devs[i++].name = imanager_dev_names[IMANAGER_SMB];
+		dev_info(imgr->dev, "iManager: smbus");
+	}
 
-	if (ec->features & IMANAGER_FEATURE_WDT)
-		devs[i++] = imanager_devs[IMANAGER_WDT];
+	if (ec->features & IMANAGER_FEATURE_WDT) {
+		devs[i++].name = imanager_dev_names[IMANAGER_WDT];
+		dev_info(imgr->dev, "iManager: wdt");
+	}
 
-#if LINUX_VERSION_CODE < KERNEL_VERSION(3, 6, 0)
-	return mfd_add_devices(imgr->dev, -1, devs, i, NULL, 0);
-#else
-	return mfd_add_devices(imgr->dev, -1, devs, i, NULL, 0, NULL);
-#endif
+	ret = mfd_add_devices(imgr->dev, PLATFORM_DEVID_NONE, devs, i, NULL, 0, NULL);
+	return ret;
 }
 
 static struct resource imanager_ioresource = {
```

**Comment by millerjs2** [comment]
Thanks, this worked!
